import type { Lesson } from '@/types/chess';
import { startingBoard, emptyBoard } from './boardUtils';

const emptyBoardState = () => ({ squares: emptyBoard(), turn: 'white' as const });

export const LESSONS: Lesson[] = [
  {
    id: 'the-board', title: 'The Chess Board', icon: '♟️',
    description: 'Learn about the 8x8 board, squares, files, and ranks.', difficulty: 'beginner',
    steps: [
      { title: 'Welcome to the Chess Board!', content: 'Chess is played on a special board with **64 squares** arranged in 8 rows and 8 columns. The squares alternate between **light** and **dark** colors!\n\nWhen you sit down to play, make sure there\'s a **light square in the bottom-right corner** nearest to you. Remember: "Light on the right!"', boardState: startingBoard() },
      { title: 'Files — the Columns', content: 'The **columns** going up and down are called **files**. Each file has a letter name:\n\n**a, b, c, d, e, f, g, h** — going from left to right.\n\nSo the leftmost column is the "a-file" and the rightmost is the "h-file".', boardState: startingBoard(), highlightedSquares: [0,1,2,3,4,5,6,7].map(r => ({ row: r, col: 3, type: 'selected' as const })) },
      { title: 'Ranks — the Rows', content: 'The **rows** going left and right are called **ranks**. Each rank has a number from **1 to 8**.\n\nRank 1 is at the bottom (where White\'s pieces start) and rank 8 is at the top (where Black\'s pieces start).', boardState: startingBoard(), highlightedSquares: [0,1,2,3,4,5,6,7].map(c => ({ row: 3, col: c, type: 'selected' as const })) },
      { title: 'The Center is Special!', content: 'The 4 squares in the very middle of the board are called **the center**: d4, e4, d5, and e5.\n\nControlling these squares is super important in chess! Strong players always try to put their pieces near the center early in the game.', boardState: emptyBoardState(), highlightedSquares: [{ row: 3, col: 3, type: 'valid-move' }, { row: 3, col: 4, type: 'valid-move' }, { row: 4, col: 3, type: 'valid-move' }, { row: 4, col: 4, type: 'valid-move' }] },
    ],
  },
  {
    id: 'the-pieces', title: 'Meet the Pieces', icon: '♞',
    description: 'Learn all 6 chess pieces and how they move.', difficulty: 'beginner',
    steps: [
      { title: 'Your Chess Army!', content: 'Each player starts with **16 pieces**:\n\n- 1 **King** 👑\n- 1 **Queen** 💎\n- 2 **Rooks** 🏰\n- 2 **Bishops** ⛪\n- 2 **Knights** 🐴\n- 8 **Pawns** ⚔️\n\nThe pieces start in the same position every single game. White always moves first!', boardState: startingBoard() },
      { title: 'The Pawn — Your Foot Soldiers', content: '**Pawns** march **forward** one square at a time. On their very first move, they can go **two squares** forward.\n\nHere\'s the tricky part: pawns **capture diagonally** — one square forward and to the side. They cannot capture straight ahead!', boardState: { squares: (() => { const b = emptyBoard(); b[4][3] = { type: 'P', color: 'white' }; return b; })(), turn: 'white' }, highlightedSquares: [{ row: 4, col: 3, type: 'selected' }, { row: 3, col: 3, type: 'valid-move' }, { row: 2, col: 3, type: 'valid-move' }, { row: 3, col: 2, type: 'capture' }, { row: 3, col: 4, type: 'capture' }] },
      { title: 'The Rook — The Straight Shooter', content: '**Rooks** move in **straight lines** — up, down, left, or right — as many squares as they want!', boardState: { squares: (() => { const b = emptyBoard(); b[3][3] = { type: 'R', color: 'white' }; return b; })(), turn: 'white' }, highlightedSquares: [{ row: 3, col: 3, type: 'selected' }, ...[0,1,2,4,5,6,7].map(c => ({ row: 3, col: c, type: 'valid-move' as const })), ...[0,1,2,4,5,6,7].map(r => ({ row: r, col: 3, type: 'valid-move' as const }))] },
      { title: 'The Bishop — The Diagonal Slider', content: '**Bishops** move **diagonally** — any number of squares in a diagonal direction.\n\nEach bishop stays on the same color square for the ENTIRE game!', boardState: { squares: (() => { const b = emptyBoard(); b[3][3] = { type: 'B', color: 'white' }; return b; })(), turn: 'white' }, highlightedSquares: [{ row: 3, col: 3, type: 'selected' }, ...[1,2,3].map(i => ({ row: 3-i, col: 3-i, type: 'valid-move' as const })).filter(s => s.row >= 0 && s.col >= 0), ...[1,2,3,4].map(i => ({ row: 3+i, col: 3+i, type: 'valid-move' as const })).filter(s => s.row < 8 && s.col < 8), ...[1,2,3].map(i => ({ row: 3-i, col: 3+i, type: 'valid-move' as const })).filter(s => s.row >= 0 && s.col < 8), ...[1,2,3,4].map(i => ({ row: 3+i, col: 3-i, type: 'valid-move' as const })).filter(s => s.row < 8 && s.col >= 0)] },
      { title: 'The Knight — The Jumping L-Shape', content: '**Knights** move in an **"L" shape**: 2 squares one direction, then 1 square sideways.\n\nThe knight is the ONLY piece that can **jump over** other pieces!', boardState: { squares: (() => { const b = emptyBoard(); b[3][3] = { type: 'N', color: 'white' }; return b; })(), turn: 'white' }, highlightedSquares: [{ row: 3, col: 3, type: 'selected' }, { row: 1, col: 2, type: 'valid-move' }, { row: 1, col: 4, type: 'valid-move' }, { row: 2, col: 1, type: 'valid-move' }, { row: 2, col: 5, type: 'valid-move' }, { row: 4, col: 1, type: 'valid-move' }, { row: 4, col: 5, type: 'valid-move' }, { row: 5, col: 2, type: 'valid-move' }, { row: 5, col: 4, type: 'valid-move' }] },
      { title: 'The Queen — The Superpower Piece', content: '**The Queen** is the most powerful piece! She can move in **ANY direction** — straight lines AND diagonally.', boardState: { squares: (() => { const b = emptyBoard(); b[3][3] = { type: 'Q', color: 'white' }; return b; })(), turn: 'white' }, highlightedSquares: [{ row: 3, col: 3, type: 'selected' }, ...[0,1,2,4,5,6,7].map(c => ({ row: 3, col: c, type: 'valid-move' as const })), ...[0,1,2,4,5,6,7].map(r => ({ row: r, col: 3, type: 'valid-move' as const })), ...[1,2,3].map(i => ({ row: 3-i, col: 3-i, type: 'valid-move' as const })).filter(s => s.row >= 0 && s.col >= 0), ...[1,2,3,4].map(i => ({ row: 3+i, col: 3+i, type: 'valid-move' as const })).filter(s => s.row < 8 && s.col < 8), ...[1,2,3].map(i => ({ row: 3-i, col: 3+i, type: 'valid-move' as const })).filter(s => s.row >= 0 && s.col < 8), ...[1,2,3,4].map(i => ({ row: 3+i, col: 3-i, type: 'valid-move' as const })).filter(s => s.row < 8 && s.col >= 0)] },
      { title: 'The King — Protect Him!', content: '**The King** can move ONE square in any direction. He\'s slow, but he\'s the most important piece!\n\nIf your king is ever trapped with no way to escape, you lose the game. That\'s **checkmate**!', boardState: { squares: (() => { const b = emptyBoard(); b[3][3] = { type: 'K', color: 'white' }; return b; })(), turn: 'white' }, highlightedSquares: [{ row: 3, col: 3, type: 'selected' }, { row: 2, col: 2, type: 'valid-move' }, { row: 2, col: 3, type: 'valid-move' }, { row: 2, col: 4, type: 'valid-move' }, { row: 3, col: 2, type: 'valid-move' }, { row: 3, col: 4, type: 'valid-move' }, { row: 4, col: 2, type: 'valid-move' }, { row: 4, col: 3, type: 'valid-move' }, { row: 4, col: 4, type: 'valid-move' }] },
    ],
  },
  {
    id: 'how-to-win', title: 'How to Win at Chess', icon: '🏆',
    description: 'Learn about check, checkmate, stalemate, and draws.', difficulty: 'beginner',
    steps: [
      { title: 'The Goal of Chess', content: 'The goal of chess is to **trap your opponent\'s king** so it can\'t escape. This is called **CHECKMATE** — and it wins the game!', boardState: startingBoard() },
      { title: 'What is Check?', content: '**Check** means your king is being attacked right now!\n\nWhen your king is in check, you MUST deal with it immediately. You have three ways to escape:\n1. **Move your king** to a safe square\n2. **Block** the attack with another piece\n3. **Capture** the piece that\'s attacking', boardState: { squares: (() => { const b = emptyBoard(); b[7][4] = { type: 'K', color: 'white' }; b[1][4] = { type: 'Q', color: 'black' }; return b; })(), turn: 'white' }, highlightedSquares: [{ row: 7, col: 4, type: 'check' }, { row: 1, col: 4, type: 'selected' }] },
      { title: 'What is Checkmate?', content: '**Checkmate** is when the king is in check AND cannot escape! This ends the game — the player who delivers checkmate WINS! 🎉', boardState: { squares: (() => { const b = emptyBoard(); b[7][4] = { type: 'K', color: 'white' }; b[7][5] = { type: 'B', color: 'white' }; b[6][3] = { type: 'P', color: 'white' }; b[6][4] = { type: 'P', color: 'white' }; b[6][5] = { type: 'P', color: 'white' }; b[4][7] = { type: 'Q', color: 'black' }; b[0][5] = { type: 'B', color: 'black' }; return b; })(), turn: 'white' }, highlightedSquares: [{ row: 7, col: 4, type: 'check' }, { row: 4, col: 7, type: 'selected' }] },
      { title: 'What is Stalemate?', content: '**Stalemate** happens when it\'s your turn, your king is NOT in check, but you have NO legal moves at all!\n\nStalemate is a **draw** — nobody wins, nobody loses!', boardState: { squares: (() => { const b = emptyBoard(); b[0][7] = { type: 'K', color: 'black' }; b[1][5] = { type: 'Q', color: 'white' }; b[2][6] = { type: 'K', color: 'white' }; return b; })(), turn: 'black' }, highlightedSquares: [{ row: 0, col: 7, type: 'selected' }, { row: 1, col: 5, type: 'check' }, { row: 2, col: 6, type: 'check' }] },
    ],
  },
  {
    id: 'special-moves', title: 'Special Moves', icon: '✨',
    description: 'Castling, en passant, and pawn promotion!', difficulty: 'beginner',
    steps: [
      { title: 'Castling — King\'s Secret Move!', content: '**Castling** is a special move where your **king** and **rook** swap places!\n\nMove the king 2 squares toward the rook, and the rook jumps over to the other side.\n\nYou can castle if neither piece has moved, there are no pieces between them, and the king is not in check.', boardState: { squares: (() => { const b = emptyBoard(); b[7][4] = { type: 'K', color: 'white' }; b[7][7] = { type: 'R', color: 'white' }; b[0][4] = { type: 'K', color: 'black' }; b[0][0] = { type: 'R', color: 'black' }; return b; })(), turn: 'white' }, highlightedSquares: [{ row: 7, col: 4, type: 'selected' }, { row: 7, col: 6, type: 'valid-move' }, { row: 7, col: 7, type: 'valid-move' }] },
      { title: 'Pawn Promotion — Become a Queen!', content: '**Pawn Promotion**: If a pawn reaches the other end of the board, it gets to become any piece it wants!\n\nAlmost everyone picks the **queen**. You can even have TWO queens at the same time!', boardState: { squares: (() => { const b = emptyBoard(); b[1][3] = { type: 'P', color: 'white' }; b[7][4] = { type: 'K', color: 'white' }; b[0][4] = { type: 'K', color: 'black' }; return b; })(), turn: 'white' }, highlightedSquares: [{ row: 1, col: 3, type: 'selected' }, { row: 0, col: 3, type: 'valid-move' }] },
      { title: 'En Passant — The Sneaky Capture!', content: '**En Passant** ("on pass-on") is the trickiest move in chess!\n\nIf an enemy pawn moves 2 squares forward and lands next to your pawn, you can capture it as if it had only moved 1 square. But you must do this **immediately**!', boardState: { squares: (() => { const b = emptyBoard(); b[3][4] = { type: 'P', color: 'white' }; b[3][5] = { type: 'P', color: 'black' }; b[7][4] = { type: 'K', color: 'white' }; b[0][4] = { type: 'K', color: 'black' }; return b; })(), turn: 'white' }, highlightedSquares: [{ row: 3, col: 4, type: 'selected' }, { row: 3, col: 5, type: 'check' }, { row: 2, col: 5, type: 'valid-move' }] },
    ],
  },
  {
    id: 'strategy-basics', title: 'Strategy Basics', icon: '🧠',
    description: 'Learn smart opening strategies and basic tactics.', difficulty: 'beginner',
    steps: [
      { title: 'Control the Center!', content: 'In chess, the most important area is the **center** of the board.\n\nPieces in the center control more squares and have more power. Try to move your pawns to d4 and e4 early in the game!', boardState: { squares: (() => { const b = startingBoard().squares.map(r => [...r]); b[4][4] = b[6][4]; b[6][4] = null; return b; })(), turn: 'black' }, highlightedSquares: [{ row: 3, col: 3, type: 'valid-move' }, { row: 3, col: 4, type: 'valid-move' }, { row: 4, col: 3, type: 'valid-move' }, { row: 4, col: 4, type: 'selected' }] },
      { title: 'Develop Your Pieces!', content: '**Development** means moving your pieces from their starting squares to active positions.\n\nMove your **knights and bishops** early! Don\'t move the same piece twice in a row.\n\n❌ Don\'t bring your queen out too early.\n✅ Do: Knights and bishops first, then castle!', boardState: { squares: (() => { const b = startingBoard().squares.map(r => [...r]); b[4][4] = b[6][4]; b[6][4] = null; b[5][5] = b[7][6]; b[7][6] = null; b[5][2] = b[7][5]; b[7][5] = null; return b; })(), turn: 'black' }, highlightedSquares: [{ row: 5, col: 5, type: 'valid-move' }, { row: 5, col: 2, type: 'valid-move' }] },
      { title: 'Keep Your King Safe!', content: 'Your **king is in danger** in the center early in the game! Castle as soon as possible to move your king to the corner behind your pawns.\n\n👑 Remember: A safe king often means a winning game!', boardState: { squares: (() => { const b = emptyBoard(); b[7][6] = { type: 'K', color: 'white' }; b[7][5] = { type: 'R', color: 'white' }; b[6][5] = { type: 'P', color: 'white' }; b[6][6] = { type: 'P', color: 'white' }; b[6][7] = { type: 'P', color: 'white' }; b[0][4] = { type: 'K', color: 'black' }; return b; })(), turn: 'white' }, highlightedSquares: [{ row: 7, col: 6, type: 'selected' }, { row: 6, col: 5, type: 'valid-move' }, { row: 6, col: 6, type: 'valid-move' }, { row: 6, col: 7, type: 'valid-move' }] },
    ],
  },
];

export function getLessonById(id: string): Lesson | undefined { return LESSONS.find(l => l.id === id); }
